### ISSUE TITLE
Setup Frontend Architecture

### ISSUE THREAD

**Issue by tobySolutions** [GuiBibeau/akeru#51]
We need to setup the frontend scaffold for the entire application.

We already decided to setup a few things in the codebase like app router and tailwind, but we would be doing a few things with streaming and a few other stuff that I think @GuiBibeau will be positioned to handle.

As of now, we only have this design to get our landing page and get inspiration for our waitlist page:

https://www.figma.com/file/B8cYeNpdAvfezzrzm0AqEk/Sprout?type=design&node-id=0-1&mode=design&t=Y0Qgfc6PWy5iL9go-0

A few things to consider when scaffolding:

- Documentation
- i18n
- Performance
- Places where we'll need RSCs

I hope this issue write-up isn't too amateurish.

**Comment by Onyelaudochukwuka** [comment]
This sounds fun , although this doesn’t seem like a design for Akeru so won’t getting the design out of the way first make scaffolding easier?

**Comment by tobySolutions** [comment]
Thank you @Onyelaudochukwuka, but, the team designed this and we were formerly Sprout, but, we're now Akeru.

**Comment by Onyelaudochukwuka** [comment]
Ohhh i see, is it ok if I take this on then?

**Comment by tobySolutions** [comment]
Oh, I just finished it now.

**Comment by Onyelaudochukwuka** [comment]
Ok💪🏽
