### ISSUE TITLE
fix tests not running properly

### ISSUE THREAD

**Issue by GuiBibeau** [GuiBibeau/akeru#58]
Since a few merges, test are not passing. Fix those

**Comment by tobySolutions** [comment]
Wait, what?

**Comment by GuiBibeau** [comment]
Need to investigate CI/CD and make sure things pass. I'm not sure when it happened but fix will be easy

**Comment by GuiBibeau** [comment]
#54 fixed some issues in CI/CD with the missing name in a package. Closing
