### ISSUE TITLE
Enhance README Documentation for Akeru.ai

### ISSUE THREAD

**Issue by resourcefulmind** [GuiBibeau/akeru#75]
The README file is the first point of interaction for potential users and contributors to Akeru.ai. As the project grows and incorporates more features, it's crucial that the README accurately reflects the capabilities and mission of Akeru.ai, providing clear and engaging content that facilitates understanding and involvement.

### Expected Outcomes:

A comprehensive, well-structured README that serves as an effective entry point for engaging new users and contributors.
Enhanced clarity on technical aspects and project roadmap, facilitating easier onboarding and collaboration.

**Comment by tobySolutions** [comment]
Fixed by #76
